kind: Service
apiVersion: v1
metadata:
  name: halekammoun
  labels:
    app: halekammoun
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: halekammoun
  type: LoadBalancer 