name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Désactiver les clonages superficiels pour une meilleure pertinence de l'analyse

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Nécessaire pour obtenir des informations sur les PR, le cas échéant
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Assurez-vous que SONAR_TOKEN est bien défini
